language: java
jdk:
- oraclejdk8

install:
  - mkdir /tmp/dynamodb
  - wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz | tar xz --directory /tmp/dynamodb

before_script:
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -port 8666 -inMemory -sharedDb &

script:
- ./gradlew '-Darchaius.deployment.environment=travis' check
